import { Router } from "express";
import { eq } from "drizzle-orm";
import { db, debtsTable, debtPaymentsTable, balanceTransactionsTable, incomesTable, profileTable } from "@workspace/db";
import { linkTelegramChat, ownerIdForTelegramChat } from "../services/telegramLink";

type ExpenseCategory = "food" | "transport" | "housing" | "utilities" | "health" | "miscellaneous";
const router = Router();
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const GEMINI_API_KEY = process.env.GEMINI_API_KEY;
const WEBHOOK_SECRET = process.env.TELEGRAM_WEBHOOK_SECRET?.trim();
const API_BASE = BOT_TOKEN ? `https://api.telegram.org/bot${BOT_TOKEN}` : null;
const LABELS: Record<string, string> = { food: "Питание", transport: "Транспорт", housing: "Жильё", utilities: "Коммунальные / связь", health: "Здоровье", miscellaneous: "Разное", debt: "Платёж по долгу", income: "Доход" };
const KEYWORDS: Record<string, ExpenseCategory> = { еда: "food", питание: "food", продукты: "food", ресторан: "food", кафе: "food", такси: "transport", транспорт: "transport", бензин: "transport", аренда: "housing", квартира: "housing", жилье: "housing", жильё: "housing", коммуналка: "utilities", интернет: "utilities", связь: "utilities", телефон: "utilities", здоровье: "health", аптека: "health", лекарства: "health" };
async function tg(method: string, body: Record<string, unknown> = {}) { if (!API_BASE) throw new Error("TELEGRAM_BOT_TOKEN не настроен"); const r = await fetch(`${API_BASE}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) throw new Error(`Telegram API: ${r.status}`); return r.json() as Promise<any>; }
async function reply(chatId: string, text: string) { await tg("sendMessage", { chat_id: chatId, text }); }
function norm(text: string) { return text.toLowerCase().replace(/ё/g, "е").replace(/[^a-zа-я0-9]+/gi, " ").trim(); }
function amountFrom(text: string) { const nums = text.match(/\d+(?:[.,]\d{1,2})?/g) || []; const raw = nums.length ? nums[nums.length - 1] : ""; const amount = Number(raw.replace(",", ".")); return Number.isFinite(amount) && amount > 0 ? amount : null; }
function categoryFrom(text: string): ExpenseCategory { const n = norm(text); for (const [key, value] of Object.entries(KEYWORDS)) if (n.includes(norm(key))) return value; return "miscellaneous"; }
function fmt(v: number) { return new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(Math.round(v)) + " сом"; }
async function ensureProfile(ownerId: string) { const [p] = await db.select().from(profileTable).where(eq(profileTable.ownerId, ownerId)).limit(1); if (p) return p; const [created] = await db.insert(profileTable).values({ ownerId, currentSavings: 0, currentBalance: 0, crisisMode: false }).returning(); return created; }
async function spend(ownerId: string, amount: number, category: ExpenseCategory, note: string) { const p = await ensureProfile(ownerId); if (p.currentBalance < amount) throw new Error(`Недостаточно денег. Баланс: ${fmt(p.currentBalance)}`); const balance = Math.round((p.currentBalance - amount) * 100) / 100; await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: balance, updatedAt: new Date() }).where(eq(profileTable.id, p.id)); await tx.insert(balanceTransactionsTable).values({ ownerId, amount: -amount, type: "expense", sourceType: "telegram", category, note }); }); return balance; }
async function receive(ownerId: string, amount: number, note: string) { const p = await ensureProfile(ownerId); const balance = Math.round((p.currentBalance + amount) * 100) / 100; const month = new Date().toISOString().slice(0, 7); await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: balance, updatedAt: new Date() }).where(eq(profileTable.id, p.id)); await tx.insert(incomesTable).values({ ownerId, source: note, projectedAmount: amount, actualAmount: amount, confidence: "HIGH", month, notes: "Telegram" }); await tx.insert(balanceTransactionsTable).values({ ownerId, amount, type: "income", sourceType: "telegram", category: "income", note }); }); return balance; }
async function debtPayment(ownerId: string, query: string, amount: number) { const debts = await db.select().from(debtsTable).where(eq(debtsTable.ownerId, ownerId)); const q = norm(query); const debt = debts.find(d => norm(d.creditorName).includes(q) || q.includes(norm(d.creditorName))) || (debts.length === 1 ? debts[0] : null); if (!debt) throw new Error(`Не нашёл долг «${query || ""}».`); const p = await ensureProfile(ownerId); if (p.currentBalance < amount) throw new Error(`Недостаточно денег. Баланс: ${fmt(p.currentBalance)}`); const balance = Math.round((p.currentBalance - amount) * 100) / 100; const newDebt = Math.max(0, debt.totalDebt - amount); await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: balance, updatedAt: new Date() }).where(eq(profileTable.id, p.id)); await tx.update(debtsTable).set({ totalDebt: newDebt }).where(eq(debtsTable.id, debt.id)); await tx.insert(debtPaymentsTable).values({ debtId: debt.id, ownerId, amount, principalPaid: amount, interestPaid: 0, paymentType: "manual", paidAt: new Date().toISOString().slice(0, 10), notes: "Telegram" }); await tx.insert(balanceTransactionsTable).values({ ownerId, amount: -amount, type: "debt_payment", sourceId: debt.id, sourceType: "debt_payment", category: "debt", note: `Платёж: ${debt.creditorName}` }); }); return { balance, debt, newDebt }; }
async function receipt(fileId: string, caption?: string): Promise<{ amount: number; merchant: string; category: ExpenseCategory; date: string | null }> { if (!BOT_TOKEN || !GEMINI_API_KEY) throw new Error("Для чеков нужен Telegram token и GEMINI_API_KEY."); const file = await tg("getFile", { file_id: fileId }); const path = file?.result?.file_path; if (!path) throw new Error("Не удалось получить файл чека."); const image = await fetch(`https://api.telegram.org/file/bot${BOT_TOKEN}/${path}`); if (!image.ok) throw new Error("Не удалось скачать чек."); const base64 = Buffer.from(await image.arrayBuffer()).toString("base64"); const ai = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ contents: [{ parts: [{ inline_data: { mime_type: "image/jpeg", data: base64 } }, { text: `Распознай чек и верни только JSON: {"amount":число,"merchant":строка,"category":"food|transport|housing|utilities|health|miscellaneous","date":"YYYY-MM-DD или null"}. Не придумывай сумму. Подпись: ${caption || "нет"}` }] }], generationConfig: { responseMimeType: "application/json", temperature: 0.1 } }) }); if (!ai.ok) throw new Error("Распознавание чека временно недоступно."); const data = await ai.json() as any; const text = String(data?.candidates?.[0]?.content?.parts?.find((p: any) => p.text)?.text || "").replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim(); const parsed = JSON.parse(text); const amount = Number(parsed.amount); if (!Number.isFinite(amount) || amount <= 0) throw new Error("Не удалось определить сумму чека."); const category: ExpenseCategory = ["food", "transport", "housing", "utilities", "health", "miscellaneous"].includes(String(parsed.category)) ? String(parsed.category) as ExpenseCategory : "miscellaneous"; return { amount, merchant: String(parsed.merchant || "Чек"), category, date: parsed.date || null }; }

export async function processTelegramBookkeepingUpdate(update: any) {
  const message = update?.message; const chatId = message?.chat?.id ? String(message.chat.id) : null; if (!chatId) return;
  const text = String(message?.text || message?.caption || "").trim();
  if (text.startsWith("/start")) { const token = text.split(/\s+/)[1]; if (token) { const result = await linkTelegramChat(token, chatId); await reply(chatId, result.status === "linked" ? "✅ Telegram подключён к ARSEN. Теперь присылай расходы, доходы, платежи по кредитам или фото чеков." : "❌ Код подключения недействителен."); return; } }
  const ownerId = await ownerIdForTelegramChat(chatId); if (!ownerId) { await reply(chatId, "🔐 Сначала подключи Telegram к ARSEN через Настройки → Telegram → Подключить."); return; }
  const photos = Array.isArray(message?.photo) ? message.photo : []; const photo = photos.length ? photos[photos.length - 1] : null;
  if (photo?.file_id) { const r = await receipt(photo.file_id, message.caption); const balance = await spend(ownerId, r.amount, r.category, `Чек: ${r.merchant}${r.date ? `, ${r.date}` : ""}`); await reply(chatId, `🧾 Чек занесён\n${r.merchant}\n${LABELS[r.category]}: -${fmt(r.amount)}\nБаланс: ${fmt(balance)}`); return; }
  if (!text) { await reply(chatId, "Пришли фото чека или сообщение с суммой."); return; }
  const amount = amountFrom(text); if (!amount) { await reply(chatId, "Напиши, например: «еда 500», «оплатил кредит мбанк 3500» или «получил зп 35000». "); return; }
  if (/(получил|получила|зп|зарплат|аванс|доход|поступил)/i.test(text)) { const balance = await receive(ownerId, amount, /зп|зарплат/i.test(text) ? "Зарплата" : "Доход"); await reply(chatId, `✅ Доход занесён\n+${fmt(amount)}\nБаланс: ${fmt(balance)}`); return; }
  if (/(кредит|кредита|долг|займ)/i.test(text) && /(оплатил|платеж|платёж|внес|заплатил)/i.test(text)) { const withoutAmount = text.replace(/\d+(?:[.,]\d+)?/g, " ").replace(/(?:кредит|кредита|долг|займ|оплатил|платеж|платёж|внес|заплатил)/gi, " ").trim(); const result = await debtPayment(ownerId, withoutAmount, amount); await reply(chatId, `✅ Платёж занесён\n${result.debt.creditorName}: -${fmt(amount)}\nОстаток долга: ${fmt(result.newDebt)}\nБаланс: ${fmt(result.balance)}`); return; }
  const category = categoryFrom(text); const name = text.replace(/\d+(?:[.,]\d+)?/g, "").trim(); const balance = await spend(ownerId, amount, category, name || LABELS[category]); await reply(chatId, `✅ Расход занесён\n${LABELS[category]}: -${fmt(amount)}\nБаланс: ${fmt(balance)}`);
}

router.post("/telegram/bookkeeping-webhook", async (req, res) => { try { if (WEBHOOK_SECRET && req.header("x-telegram-bot-api-secret-token") !== WEBHOOK_SECRET) { res.status(401).json({ error: "Invalid Telegram webhook secret" }); return; } await processTelegramBookkeepingUpdate(req.body); res.json({ ok: true }); } catch (error) { console.error("[telegram-bookkeeping]", error); const chatId = req.body?.message?.chat?.id; if (chatId) { try { await reply(String(chatId), `⚠️ ${error instanceof Error ? error.message : "Не удалось обработать операцию."}`); } catch {} } res.json({ ok: true }); } });
export default router;
