import { Router } from "express";
import { eq } from "drizzle-orm";
import { GoogleGenAI } from "@google/genai";
import { db, debtsTable, debtPaymentsTable, balanceTransactionsTable, incomesTable, profileTable } from "@workspace/db";
import { requireAuth } from "../middlewares/requireAuth";
import { createTelegramLinkToken, getTelegramLinkStatus, linkTelegramChat, ownerIdForTelegramChat, unlinkTelegramChat } from "../services/telegramLink";

const router = Router();
const BOT_TOKEN = process.env.TELEGRAM_BOT_TOKEN;
const PUBLIC_URL = process.env.PUBLIC_APP_URL || process.env.RENDER_EXTERNAL_URL || process.env.REPLIT_APP_URL || "https://arsen-finance.onrender.com";
const genai = process.env.GEMINI_API_KEY ? new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }) : null;
const API_BASE = BOT_TOKEN ? `https://api.telegram.org/bot${BOT_TOKEN}` : null;
const CATEGORY_MAP: Record<string, string> = { еда: "food", продукты: "food", ресторан: "food", кафе: "food", обед: "food", ужин: "food", такси: "transport", транспорт: "transport", бензин: "transport", машина: "transport", аренда: "housing", квартира: "housing", жилье: "housing", жильё: "housing", коммуналка: "utilities", интернет: "utilities", связь: "utilities", телефон: "utilities", здоровье: "health", аптека: "health", врач: "health", лекарства: "health" };
const CATEGORY_LABEL: Record<string, string> = { housing: "Жильё", food: "Питание", transport: "Транспорт", utilities: "Коммунальные / связь", health: "Здоровье", miscellaneous: "Разное", debt: "Платёж по долгу", income: "Доход" };
async function telegram(method: string, body: Record<string, unknown> = {}) { if (!API_BASE) throw new Error("TELEGRAM_BOT_TOKEN is not configured"); const response = await fetch(`${API_BASE}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); return response.json() as Promise<any>; }
async function sendMessage(chatId: string, text: string) { return telegram("sendMessage", { chat_id: chatId, text }); }
async function typing(chatId: string) { try { await telegram("sendChatAction", { chat_id: chatId, action: "typing" }); } catch {} }
function normalize(s: string) { return s.toLowerCase().replace(/ё/g, "е").replace(/[^a-zа-я0-9]+/gi, " ").trim(); }
function lastAmount(text: string) { const matches = text.replace(/\s/g, " ").match(/(?:^|\s)(\d+(?:[.,]\d{1,2})?)(?:\s*(?:сом|с|kgs|кг))?(?=\s|$)/gi) || []; const raw = matches.length ? matches[matches.length - 1].match(/\d+(?:[.,]\d{1,2})?/i)?.[0] : undefined; return raw ? Number(raw.replace(",", ".")) : null; }
function categoryFromText(text: string) { const normalized = normalize(text); for (const [keyword, category] of Object.entries(CATEGORY_MAP)) if (normalized.includes(normalize(keyword))) return category; return "miscellaneous"; }
function expenseName(text: string, category: string) { const cleaned = text.replace(/\d+(?:[.,]\d{1,2})?/g, " ").replace(/\b(?:сом|с|kgs|кг)\b/gi, " ").trim(); return cleaned.length > 1 ? cleaned.slice(0, 80) : (CATEGORY_LABEL[category] || "Расход"); }
async function ensureBalance(ownerId: string) { const [profile] = await db.select().from(profileTable).where(eq(profileTable.ownerId, ownerId)).limit(1); if (profile) return profile; const [created] = await db.insert(profileTable).values({ ownerId, currentSavings: 0, currentBalance: 0, crisisMode: false }).returning(); return created; }
async function recordExpense(ownerId: string, amount: number, category: string, name: string, note?: string) { const profile = await ensureBalance(ownerId); if (profile.currentBalance < amount) throw new Error(`Недостаточно денег на балансе. Сейчас ${Math.round(profile.currentBalance)} сом.`); const newBalance = Math.round((profile.currentBalance - amount) * 100) / 100; await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: newBalance, updatedAt: new Date() }).where(eq(profileTable.id, profile.id)); await tx.insert(balanceTransactionsTable).values({ ownerId, amount: -amount, type: "expense", sourceType: "telegram", category, note: note || name }); }); return newBalance; }
async function recordIncome(ownerId: string, amount: number, source: string) { const profile = await ensureBalance(ownerId); const newBalance = Math.round((profile.currentBalance + amount) * 100) / 100; const month = new Date().toISOString().slice(0, 7); await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: newBalance, updatedAt: new Date() }).where(eq(profileTable.id, profile.id)); await tx.insert(incomesTable).values({ ownerId, source, projectedAmount: amount, actualAmount: amount, confidence: "HIGH", month, notes: "Добавлено через Telegram" }); await tx.insert(balanceTransactionsTable).values({ ownerId, amount, type: "income", sourceType: "telegram", category: "income", note: source }); }); return newBalance; }
async function recordDebtPayment(ownerId: string, creditorQuery: string, amount: number) { const debts = await db.select().from(debtsTable).where(eq(debtsTable.ownerId, ownerId)); const q = normalize(creditorQuery); const debt = debts.find(d => normalize(d.creditorName).includes(q) || q.includes(normalize(d.creditorName))) || (debts.length === 1 ? debts[0] : null); if (!debt) throw new Error(`Не нашёл кредит «${creditorQuery}». Напиши точное название из раздела долгов.`); const profile = await ensureBalance(ownerId); if (profile.currentBalance < amount) throw new Error(`Недостаточно денег на балансе. Сейчас ${Math.round(profile.currentBalance)} сом.`); const newDebt = Math.max(0, debt.totalDebt - amount); const newBalance = Math.round((profile.currentBalance - amount) * 100) / 100; await db.transaction(async tx => { await tx.update(profileTable).set({ currentBalance: newBalance, updatedAt: new Date() }).where(eq(profileTable.id, profile.id)); await tx.update(debtsTable).set({ totalDebt: newDebt }).where(eq(debtsTable.id, debt.id)); await tx.insert(debtPaymentsTable).values({ debtId: debt.id, ownerId, amount, principalPaid: amount, interestPaid: 0, paymentType: "manual", paidAt: new Date().toISOString().slice(0, 10), notes: "Добавлено через Telegram" }); await tx.insert(balanceTransactionsTable).values({ ownerId, amount: -amount, type: "debt_payment", sourceId: debt.id, sourceType: "debt_payment", category: "debt", note: `Платёж: ${debt.creditorName}` }); }); return { newBalance, debt, newDebt }; }
async function parseReceipt(fileId: string, caption?: string) { if (!genai) throw new Error("Для распознавания чеков нужен GEMINI_API_KEY."); const fileResult = await telegram("getFile", { file_id: fileId }); const path = fileResult?.result?.file_path; if (!path) throw new Error("Telegram не вернул файл чека."); const imageResponse = await fetch(`https://api.telegram.org/file/bot${BOT_TOKEN}/${path}`); if (!imageResponse.ok) throw new Error("Не удалось скачать чек из Telegram."); const buffer = Buffer.from(await imageResponse.arrayBuffer()); if (buffer.length > 19 * 1024 * 1024) throw new Error("Фото чека слишком большое."); const response = await genai.models.generateContent({ model: "gemini-2.0-flash", contents: [{ inlineData: { mimeType: "image/jpeg", data: buffer.toString("base64") } }, { text: `Распознай этот финансовый чек. Верни только JSON без markdown: {"amount":число,"merchant":строка,"category":"food|transport|housing|utilities|health|miscellaneous","date":"YYYY-MM-DD или null"}. Если сумму определить нельзя, amount=null. Учитывай подпись пользователя: ${caption || "нет"}. Не придумывай сумму.` }], config: { responseMimeType: "application/json", temperature: 0.1 } }); const text = (response.text || "").replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim(); const parsed = JSON.parse(text); if (!Number.isFinite(Number(parsed.amount)) || Number(parsed.amount) <= 0) throw new Error("Не смог уверенно определить итоговую сумму чека."); const category = ["food", "transport", "housing", "utilities", "health", "miscellaneous"].includes(String(parsed.category)) ? String(parsed.category) : "miscellaneous"; return { amount: Number(parsed.amount), merchant: String(parsed.merchant || "Чек"), category, date: parsed.date || null }; }
async function processText(ownerId: string, chatId: string, text: string) { const normalized = normalize(text); if (/^\/?(?:help|помощь)/.test(normalized)) { await sendMessage(chatId, "Я умею:\n• «еда 500» — расход\n• «такси 300» — расход с категорией\n• «оплатил кредит мбанк 3500» — платёж по долгу\n• «получил зп 35000» — доход\n• отправь фото чека — распознаю и занесу автоматически."); return; } const amount = lastAmount(text); if (!amount || amount <= 0) { await sendMessage(chatId, "Не понял сумму. Пример: «еда 500», «получил зп 35000» или «оплатил кредит мбанк 3500»."); return; } if (/(?:получил|получила|зарплат|зп|аванс|доход|пришли деньги|поступил)/i.test(text)) { const balance = await recordIncome(ownerId, amount, /зп|зарплат/i.test(text) ? "Зарплата" : "Доход"); await sendMessage(chatId, `✅ Доход занесён\n+${Math.round(amount)} сом\nБаланс: ${Math.round(balance)} сом`); return; } if (/(?:кредит|кредита|кредиту|долг|займ)/i.test(text) && /(?:оплатил|оплата|платеж|платёж|внес|заплатил)/i.test(text)) { const withoutAmount = text.replace(/\d+(?:[.,]\d{1,2})?/g, " ").replace(/\b(?:сом|с)\b/gi, " ").trim(); const creditor = withoutAmount.replace(/(?:оплатил|оплата|платеж|платёж|внес|заплатил|кредит|кредита|кредиту|долг|займ)/gi, " ").replace(/\s+/g, " ").trim(); const result = await recordDebtPayment(ownerId, creditor || "кредит", amount); await sendMessage(chatId, `✅ Платёж занесён\n${result.debt.creditorName}: -${Math.round(amount)} сом\nОстаток долга: ${Math.round(result.newDebt)} сом\nБаланс: ${Math.round(result.newBalance)} сом`); return; } const category = categoryFromText(text); const name = expenseName(text, category); const balance = await recordExpense(ownerId, amount, category, name); await sendMessage(chatId, `✅ Расход занесён\n${CATEGORY_LABEL[category] || "Разное"}: -${Math.round(amount)} сом\nБаланс: ${Math.round(balance)} сом`); }
async function processUpdate(update: any) { const message = update?.message; const chatId = message?.chat?.id ? String(message.chat.id) : null; if (!chatId) return { handled: false, reason: "no_chat" }; const text = String(message?.text || message?.caption || "").trim(); if (text.startsWith("/start")) { const token = text.split(/\s+/)[1]; if (token) { const result = await linkTelegramChat(token, chatId); if (result.status === "linked") { await sendMessage(chatId, "✅ Telegram подключён к ARSEN. Теперь присылай расходы, доходы, платежи по кредитам или фото чеков."); return { handled: true, reason: "linked" }; } if (result.status === "chat_already_linked") { await sendMessage(chatId, "Этот Telegram уже подключён к другому аккаунту ARSEN."); return { handled: true, reason: "already_linked" }; } await sendMessage(chatId, "Ссылка устарела или неверна. Создай новый код подключения в ARSEN."); return { handled: true, reason: "invalid_link" }; } } const ownerId = await ownerIdForTelegramChat(chatId); if (!ownerId) { await sendMessage(chatId, "🔐 Сначала подключи Telegram к ARSEN через Настройки → Telegram → Подключить."); return { handled: true, reason: "not_linked" }; } await typing(chatId); const photos = Array.isArray(message?.photo) ? message.photo : []; const photo = photos.length ? photos[photos.length - 1] : null; if (photo?.file_id) { try { const receipt = await parseReceipt(photo.file_id, message.caption); const balance = await recordExpense(ownerId, receipt.amount, receipt.category, receipt.merchant, `Чек: ${receipt.merchant}${receipt.date ? `, ${receipt.date}` : ""}`); await sendMessage(chatId, `🧾 Чек распознан и занесён\n${receipt.merchant}\n${CATEGORY_LABEL[receipt.category] || "Разное"}: -${Math.round(receipt.amount)} сом\nБаланс: ${Math.round(balance)} сом`); } catch (error) { await sendMessage(chatId, `Не смог обработать чек: ${error instanceof Error ? error.message : "неизвестная ошибка"}`); } return { handled: true, reason: "receipt" }; } if (text) { try { await processText(ownerId, chatId, text); } catch (error) { await sendMessage(chatId, `Не удалось занести операцию: ${error instanceof Error ? error.message : "неизвестная ошибка"}`); } return { handled: true, reason: "text" }; } await sendMessage(chatId, "Пришли текст с суммой или фото чека."); return { handled: true, reason: "unsupported" }; }
router.post("/telegram/setup", requireAuth, async (_req, res) => { if (!BOT_TOKEN) { res.status(503).json({ registered: false, url: null, error: "TELEGRAM_BOT_TOKEN is not configured" }); return; } const url = `${PUBLIC_URL.replace(/\/$/, "")}/api/telegram/webhook`; const result = await telegram("setWebhook", { url, allowed_updates: ["message"] }); const info = await telegram("getWebhookInfo"); res.json({ registered: Boolean(result.ok), url, pendingUpdateCount: info?.result?.pending_update_count ?? 0 }); });
router.post("/telegram/webhook", async (req, res) => { try { await processUpdate(req.body); res.json({ ok: true, handled: true }); } catch (error) { console.error("Telegram webhook error", error); res.json({ ok: true, handled: false, reason: "processing_error" }); } });
router.get("/telegram/webhook", async (_req, res) => { if (!BOT_TOKEN) { res.status(503).json({ ok: false, error: "TELEGRAM_BOT_TOKEN is not configured" }); return; } res.json(await telegram("getWebhookInfo")); });
router.post("/telegram/updates", requireAuth, async (_req, res) => res.json({ ok: true, message: "Webhook mode is active. Updates are processed immediately." }));
router.post("/telegram/link-token", requireAuth, async (req, res) => { const result = await createTelegramLinkToken(req.user!.id); const usernameResult = BOT_TOKEN ? await telegram("getMe") : null; const username = usernameResult?.result?.username; res.json({ connected: false, command: `/start ${result.token}`, deepLink: username ? `https://t.me/${username}?start=${result.token}` : `${PUBLIC_URL}/telegram?token=${result.token}`, expiresAt: result.expiresAt.toISOString() }); });
router.get("/telegram/status", requireAuth, async (req, res) => res.json(await getTelegramLinkStatus(req.user!.id)));
router.delete("/telegram/link", requireAuth, async (req, res) => res.json(await unlinkTelegramChat(req.user!.id)));
export default router;
