import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useGetDashboardSummary, useUpdateProfile, useGetProfile, useGetProjectsSummary } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Skeleton } from "@/components/ui/skeleton";
import { TrendingUp, TrendingDown, Wallet, Receipt, ShieldAlert, Activity, AlertTriangle, BrainCircuit, BarChart3, PiggyBank, HeartHandshake, ShieldCheck, Beaker, ArrowDownRight, ArrowUpRight, CreditCard } from "lucide-react";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell, Legend } from "recharts";
import { Link } from "wouter";
import { useToast } from "@/hooks/use-toast";

const fmt = (val: number) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(Math.round(val)) + "\u00a0сом";
const fmtCompact = (v: number) => new Intl.NumberFormat("ru-RU", { notation: "compact", maximumFractionDigits: 1 }).format(v);
const CATEGORY_NAMES: Record<string, string> = { housing: "Жильё", food: "Питание", transport: "Транспорт", utilities: "Коммунальные / связь", health: "Здоровье", miscellaneous: "Разное", debt: "Платежи по долгам", income: "Доходы", withdrawal: "Списания", allocation: "Распределение", goals: "Финансовые цели", other: "Прочее" };

type Detailed = {
  currentBalance: number;
  currentMonth: string;
  currentMonthIncome: number;
  currentMonthOutflow: number;
  currentMonthNet: number;
  plannedMonthlyExpenses: number;
  categoryBreakdown: Array<{ category: string; label: string; amount: number }>;
  debtPayments: Array<{ creditorName: string; amount: number }>;
  monthlyCashFlow: Array<{ month: string; income: number; expenses: number; net: number }>;
  recentTransactions: Array<{ id: number; amount: number; type: string; category: string; categoryLabel: string; note?: string | null; createdAt: string }>;
};

async function getDetailed(): Promise<Detailed> { const r = await fetch("/api/dashboard/detailed"); if (!r.ok) throw new Error("Не удалось загрузить детализацию"); return r.json(); }

function MetricCard({ title, value, subtext, icon: Icon, trend, colorClass }: any) { return <Card className="hover-elevate"><CardHeader className="flex flex-row items-center justify-between pb-2"><CardTitle className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">{title}</CardTitle><Icon className={`h-4 w-4 ${colorClass}`} /></CardHeader><CardContent><div className="text-xl font-bold tracking-tight mb-1">{value}</div>{subtext && <p className="text-xs text-muted-foreground flex items-center gap-1">{trend === "up" && <TrendingUp className="h-3 w-3 text-emerald-500" />}{trend === "down" && <TrendingDown className="h-3 w-3 text-destructive" />}<span>{subtext}</span></p>}</CardContent></Card>; }
function RunwayBadge({ months }: { months: number }) { let color = "bg-destructive text-destructive-foreground"; if (months > 6) color = "bg-emerald-500 text-white"; else if (months >= 3) color = "bg-amber-500 text-white"; return <Badge className={`${color} px-2.5 py-1 text-sm font-bold border-none`}>{months.toFixed(1)} мес.</Badge>; }

export default function Dashboard() {
  const queryClient = useQueryClient(); const { toast } = useToast();
  const { data: summary, isLoading: isSummaryLoading } = useGetDashboardSummary({ query: { queryKey: ["/api/dashboard"] } });
  const { data: profile, isLoading: isProfileLoading } = useGetProfile({ query: { queryKey: ["/api/profile"] } });
  const { data: projectsSummary } = useGetProjectsSummary({ query: { queryKey: ["/api/projects/summary"] } });
  const detailed = useQuery({ queryKey: ["/api/dashboard/detailed"], queryFn: getDetailed, staleTime: 15_000 });
  const updateProfile = useUpdateProfile();
  const handleCrisisToggle = (checked: boolean) => { updateProfile.mutate({ data: { crisisMode: checked } }, { onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/dashboard"] }); queryClient.invalidateQueries({ queryKey: ["/api/profile"] }); toast({ title: checked ? "КРИЗИСНЫЙ РЕЖИМ ВКЛЮЧЁН" : "Обычный режим восстановлен", description: checked ? "Считаются только обязательные траты." : "Возврат к обычному планированию.", variant: checked ? "destructive" : "default" }); } }); };
  if (isSummaryLoading || isProfileLoading || !summary || !profile || detailed.isLoading) return <div className="space-y-6"><Skeleton className="h-12 w-64" /><div className="grid grid-cols-2 lg:grid-cols-5 gap-4">{[1,2,3,4,5].map(i => <Skeleton key={i} className="h-28" />)}</div><Skeleton className="h-96 w-full" /></div>;
  const d = detailed.data;
  const monthlyData = (d?.monthlyCashFlow ?? []).map(m => ({ month: m.month.slice(5), "Доходы": Math.round(m.income), "Расходы": Math.round(m.expenses), "Чистый поток": Math.round(m.net) }));
  const categoryData = (d?.categoryBreakdown ?? []).slice(0, 8);
  const actualBalance = d?.currentBalance ?? profile.currentBalance ?? 0;
  const outflow = d?.currentMonthOutflow ?? 0;
  const income = d?.currentMonthIncome ?? 0;
  const net = d?.currentMonthNet ?? 0;
  const hasProjects = (projectsSummary?.projects?.length ?? 0) > 0;
  const recent = d?.recentTransactions ?? [];
  return <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Обзор финансов</h1><p className="text-muted-foreground mt-1">Баланс, реальные движения денег, категории и долги — в одном месте.</p></div><Card className={`border-2 ${profile.crisisMode ? "border-destructive bg-destructive/5" : "border-border"}`}><CardContent className="p-4 flex items-center gap-4"><ShieldAlert className={`h-6 w-6 ${profile.crisisMode ? "text-destructive" : "text-muted-foreground"}`} /><div><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Режим</p><p className={`text-base font-bold ${profile.crisisMode ? "text-destructive" : ""}`}>{profile.crisisMode ? "Кризисный" : "Обычный"}</p></div><div className="w-px h-8 bg-border mx-1" /><Switch checked={profile.crisisMode} onCheckedChange={handleCrisisToggle} className={profile.crisisMode ? "data-[state=checked]:bg-destructive" : ""} /></CardContent></Card></div>
    <div><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground mb-3">💼 Личные финансы</p><div className="grid grid-cols-2 md:grid-cols-5 gap-4"><MetricCard title="Свободный остаток" value={fmt(actualBalance)} subtext="Доступно сейчас" icon={Wallet} trend={actualBalance > 0 ? "up" : "down"} colorClass={actualBalance > 0 ? "text-emerald-500" : "text-destructive"} /><MetricCard title="Доходы за месяц" value={fmt(income)} subtext="Фактические поступления" icon={ArrowUpRight} colorClass="text-emerald-500" /><MetricCard title="Списано за месяц" value={fmt(outflow)} subtext="Все реальные списания" icon={ArrowDownRight} colorClass="text-destructive" /><MetricCard title="Чистый поток" value={fmt(net)} subtext="Доходы − списания" icon={Activity} trend={net >= 0 ? "up" : "down"} colorClass={net >= 0 ? "text-emerald-500" : "text-destructive"} /><MetricCard title="План трат" value={fmt(d?.plannedMonthlyExpenses ?? summary.totalMonthlyExpenses)} subtext="Регулярные расходы / мес" icon={Receipt} colorClass="text-primary" /></div></div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <Card className="lg:col-span-2"><CardHeader><CardTitle>Фактический денежный поток</CardTitle><CardDescription>Реальные операции с текущего баланса за последние 6 месяцев</CardDescription></CardHeader><CardContent className="h-[330px]">{monthlyData.length ? <ResponsiveContainer width="100%" height="100%"><BarChart data={monthlyData} margin={{ top: 10, right: 10, left: 0, bottom: 5 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} /><XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" fontSize={11} tickLine={false} axisLine={false} /><YAxis stroke="hsl(var(--muted-foreground))" fontSize={11} tickLine={false} axisLine={false} tickFormatter={fmtCompact} width={55} /><Tooltip contentStyle={{ backgroundColor: "hsl(var(--card))", borderColor: "hsl(var(--border))", borderRadius: "8px" }} formatter={(v: number, name: string) => [fmt(v), name]} /><Legend fontSize={11} /><Bar dataKey="Доходы" fill="hsl(var(--primary))" radius={[3,3,0,0]} maxBarSize={34} /><Bar dataKey="Расходы" fill="hsl(var(--destructive))" radius={[3,3,0,0]} maxBarSize={34} /><Bar dataKey="Чистый поток" fill="hsl(var(--chart-3))" radius={[3,3,0,0]} maxBarSize={34} /></BarChart></ResponsiveContainer> : <div className="h-full flex items-center justify-center text-muted-foreground">Пока недостаточно операций для графика.</div>}</CardContent></Card>
      <Card><CardHeader><CardTitle>Куда ушли деньги</CardTitle><CardDescription>Фактические списания текущего месяца</CardDescription></CardHeader><CardContent className="space-y-3">{categoryData.length ? categoryData.map((x, i) => <div key={x.category} className="space-y-1.5"><div className="flex justify-between gap-3 text-sm"><span className="truncate">{CATEGORY_NAMES[x.category] || x.label}</span><span className="font-mono font-semibold">{fmt(x.amount)}</span></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(3, Math.min(100, outflow ? (x.amount / outflow) * 100 : 0))}%` }} /></div></div>) : <div className="py-10 text-center text-muted-foreground">В этом месяце списаний пока нет.</div>}</CardContent></Card>
    </div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <Card><CardHeader><CardTitle>Платежи по долгам</CardTitle><CardDescription>Реально списано по кредитам за месяц</CardDescription></CardHeader><CardContent className="space-y-3">{d?.debtPayments?.length ? d.debtPayments.map(x => <div key={x.creditorName} className="flex items-center justify-between gap-3 rounded-lg border p-3"><div className="flex items-center gap-3 min-w-0"><div className="p-2 rounded-md bg-destructive/10"><CreditCard className="h-4 w-4 text-destructive" /></div><span className="truncate font-medium">{x.creditorName}</span></div><span className="font-mono font-semibold text-destructive">-{fmt(x.amount)}</span></div>) : <div className="py-10 text-center text-muted-foreground">Платежей по долгам в этом месяце нет.</div>}</CardContent></Card>
      <Card className="lg:col-span-2"><CardHeader><CardTitle>Последние операции</CardTitle><CardDescription>Все реальные движения денег: доходы, расходы, кредиты, цели и распределения</CardDescription></CardHeader><CardContent>{recent.length ? <div className="divide-y">{recent.slice(0, 12).map(tx => <div key={tx.id} className="py-3 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><div className={`p-2 rounded-md ${tx.amount >= 0 ? "bg-emerald-500/10" : "bg-destructive/10"}`}>{tx.amount >= 0 ? <ArrowUpRight className="h-4 w-4 text-emerald-500" /> : <ArrowDownRight className="h-4 w-4 text-destructive" />}</div><div className="min-w-0"><div className="font-medium truncate">{tx.note || tx.categoryLabel}</div><div className="text-xs text-muted-foreground">{tx.categoryLabel} · {new Date(tx.createdAt).toLocaleString("ru-RU", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</div></div></div><div className={`font-mono font-semibold whitespace-nowrap ${tx.amount >= 0 ? "text-emerald-500" : "text-destructive"}`}>{tx.amount >= 0 ? "+" : "−"}{fmt(Math.abs(tx.amount))}</div></div>)}</div> : <div className="py-10 text-center text-muted-foreground">Операций пока нет.</div>}</CardContent></Card>
    </div>
    {hasProjects && <div><div className="flex items-center justify-between mb-3"><p className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">📊 Бизнес-проекты</p><Link href="/projects"><Button variant="ghost" size="sm" className="text-xs">Все проекты →</Button></Link></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><MetricCard title="Общий оборот" value={fmt(summary.totalProjectRevenue ?? 0)} subtext="Gross Revenue" icon={BarChart3} colorClass="text-primary" /><MetricCard title="Чистая прибыль" value={fmt(summary.totalProjectNetProfit ?? 0)} subtext="Net Profit" icon={TrendingUp} trend={(summary.totalProjectNetProfit ?? 0) >= 0 ? "up" : "down"} colorClass={(summary.totalProjectNetProfit ?? 0) >= 0 ? "text-emerald-500" : "text-destructive"} /><MetricCard title="Дивиденды" value={fmt(summary.totalProjectDividends ?? 0)} subtext="Выплачено на личный счёт" icon={PiggyBank} colorClass="text-amber-500" /></div></div>}
    <div className="grid grid-cols-1 md:grid-cols-4 gap-3"><Link href="/expenses"><Button variant="outline" className="w-full justify-start h-auto py-3"><Receipt className="mr-3 h-4 w-4" /><div className="text-left"><div className="font-semibold">Расходы</div><div className="text-xs text-muted-foreground">Планы + реальные списания</div></div></Button></Link><Link href="/debts"><Button variant="outline" className="w-full justify-start h-auto py-3"><CreditCard className="mr-3 h-4 w-4" /><div className="text-left"><div className="font-semibold">Долги</div><div className="text-xs text-muted-foreground">Баланс и платежи</div></div></Button></Link><Link href="/goals"><Button variant="outline" className="w-full justify-start h-auto py-3"><PiggyBank className="mr-3 h-4 w-4" /><div className="text-left"><div className="font-semibold">Финансовые цели</div><div className="text-xs text-muted-foreground">Деньги зарезервированы</div></div></Button></Link><Link href="/ai"><Button variant="outline" className="w-full justify-start h-auto py-3"><BrainCircuit className="mr-3 h-4 w-4" /><div className="text-left"><div className="font-semibold">ИИ-советник</div><div className="text-xs text-muted-foreground">Анализ бюджета</div></div></Button></Link></div>
  </div>;
}
