import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useListExpenses, useCreateExpense, useUpdateExpense, useDeleteExpense, useGetBurnRate, Expense } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Badge } from "@/components/ui/badge";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Receipt, Plus, Trash2, Pencil, Home, Utensils, Car, Zap, HeartPulse, MoreHorizontal, ArrowDownRight, CreditCard } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip } from "recharts";

const fmt = (val: number) => new Intl.NumberFormat("ru-RU", { maximumFractionDigits: 0 }).format(Math.round(val)) + " сом";
const CATEGORIES = ["housing", "food", "transport", "utilities", "health", "miscellaneous"] as const;
const schema = z.object({ category: z.enum(CATEGORIES), name: z.string().min(1), amount: z.coerce.number().min(0.01), frequency: z.enum(["daily", "monthly"]), isEssential: z.boolean() });
const CATEGORY_ICONS: Record<string, any> = { housing: Home, food: Utensils, transport: Car, utilities: Zap, health: HeartPulse, miscellaneous: MoreHorizontal };
const COLORS: Record<string, string> = { housing: "hsl(var(--primary))", food: "hsl(var(--chart-2))", transport: "hsl(var(--chart-3))", utilities: "hsl(var(--chart-4))", health: "hsl(var(--chart-5))", miscellaneous: "hsl(var(--muted-foreground))" };
const NAMES: Record<string, string> = { housing: "Жильё", food: "Питание", transport: "Транспорт", utilities: "Коммунальные / связь", health: "Здоровье", miscellaneous: "Разное", debt: "Платежи по долгам", income: "Доход", withdrawal: "Списания", allocation: "Распределение", goals: "Финансовые цели", other: "Прочее" };
type Actual = { recentTransactions: Array<{ id: number; amount: number; type: string; category: string; categoryLabel: string; note?: string | null; createdAt: string }> };
async function getActual(): Promise<Actual> { const r = await fetch("/api/dashboard/detailed"); if (!r.ok) throw new Error(); return r.json(); }
type Item = Expense & { frequency?: "daily" | "monthly" };

type FormValues = z.infer<typeof schema>;
export default function Expenses() {
  const qc = useQueryClient(); const { toast } = useToast();
  const { data: expenses, isLoading } = useListExpenses({ query: { queryKey: ["/api/expenses"] } });
  const { data: burn, isLoading: burnLoading } = useGetBurnRate({ query: { queryKey: ["/api/expenses/burn-rate"] } });
  const actual = useQuery({ queryKey: ["/api/dashboard/detailed"], queryFn: getActual, staleTime: 15_000 });
  const create = useCreateExpense(); const update = useUpdateExpense(); const remove = useDeleteExpense();
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Item | null>(null); const [onlyEssential, setOnlyEssential] = useState(false);
  const form = useForm<FormValues>({ resolver: zodResolver(schema), defaultValues: { category: "miscellaneous", name: "", amount: 0, frequency: "monthly", isEssential: false } });
  const frequency = form.watch("frequency");
  const invalidate = () => { ["/api/expenses", "/api/expenses/burn-rate", "/api/balance", "/api/dashboard", "/api/dashboard/detailed"].forEach(k => qc.invalidateQueries({ queryKey: [k] })); };
  const edit = (item?: Expense) => { if (item) { const x = item as Item; setEditing(x); form.reset({ category: x.category as FormValues["category"], name: x.name, amount: x.amount, frequency: x.frequency ?? "monthly", isEssential: x.isEssential }); } else { setEditing(null); form.reset({ category: "miscellaneous", name: "", amount: 0, frequency: "monthly", isEssential: false }); } setOpen(true); };
  const submit = (data: FormValues) => { const done = () => { invalidate(); setOpen(false); toast({ title: editing ? "Расход обновлён" : "Расход добавлен и списан с баланса" }); }; if (editing) update.mutate({ id: editing.id, data: data as any }, { onSuccess: done }); else create.mutate({ data: data as any }, { onSuccess: done }); };
  const del = (id: number) => { if (!confirm("Удалить расход и вернуть сумму на баланс?")) return; remove.mutate({ id }, { onSuccess: () => { invalidate(); toast({ title: "Расход удалён" }); } }); };
  if (isLoading || burnLoading) return <div className="space-y-6"><Skeleton className="h-12 w-64" /><Skeleton className="h-72 w-full" /></div>;
  const rows = ((expenses || []) as Item[]).filter(x => onlyEssential ? x.isEssential : true);
  const chart = burn?.byCategory.map(x => ({ name: NAMES[x.category] || x.category, value: x.total, color: COLORS[x.category] || COLORS.miscellaneous })) || [];
  const actualOutflows = actual.data?.recentTransactions.filter(x => x.amount < 0) || [];
  return <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
    <div className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h1 className="text-3xl font-bold tracking-tight">Мои расходы</h1><p className="text-muted-foreground mt-1">Регулярные расходы + все реальные списания с текущего баланса.</p></div><Button size="lg" onClick={() => edit()}><Plus className="mr-2 h-4 w-4" /> Добавить расход</Button></div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent className="sm:max-w-[500px]"><DialogHeader><DialogTitle>{editing ? "Редактировать расход" : "Новый расход"}</DialogTitle></DialogHeader><Form {...form}><form onSubmit={form.handleSubmit(submit)} className="space-y-4"><FormField control={form.control} name="name" render={({ field }) => <FormItem><FormLabel>Название</FormLabel><FormControl><Input {...field} placeholder="Продукты, бензин, аренда…" /></FormControl><FormMessage /></FormItem>} /><div className="grid grid-cols-2 gap-4"><FormField control={form.control} name="amount" render={({ field }) => <FormItem><FormLabel>{frequency === "daily" ? "Сумма в день (сом)" : "Сумма в месяц (сом)"}</FormLabel><FormControl><Input type="number" min="0.01" step="1" {...field} /></FormControl><FormMessage /></FormItem>} /><FormField control={form.control} name="frequency" render={({ field }) => <FormItem><FormLabel>Периодичность</FormLabel><Select value={field.value} onValueChange={field.onChange}><FormControl><SelectTrigger><SelectValue /></SelectTrigger></FormControl><SelectContent><SelectItem value="daily">Каждый день</SelectItem><SelectItem value="monthly">Каждый месяц</SelectItem></SelectContent></Select></FormItem>} /></div><FormField control={form.control} name="category" render={({ field }) => <FormItem><FormLabel>Категория</FormLabel><Select value={field.value} onValueChange={field.onChange}><FormControl><SelectTrigger><SelectValue /></SelectTrigger></FormControl><SelectContent>{CATEGORIES.map(c => <SelectItem key={c} value={c}>{NAMES[c]}</SelectItem>)}</SelectContent></Select></FormItem>} /><FormField control={form.control} name="isEssential" render={({ field }) => <FormItem className="flex items-center justify-between rounded-lg border p-4"><div><FormLabel>Обязательный расход</FormLabel><p className="text-xs text-muted-foreground">Учитывается в минимальной стоимости жизни.</p></div><FormControl><Switch checked={field.value} onCheckedChange={field.onChange} /></FormControl></FormItem>} /><div className="text-xs text-muted-foreground rounded-lg border bg-muted/30 p-3">Ежедневный план ×30 используется только в аналитике. Фактическое списание — ровно введённая сумма.</div><div className="flex justify-end"><Button type="submit">{editing ? "Сохранить" : "Добавить"}</Button></div></form></Form></DialogContent></Dialog>
    {burn && <div className="grid grid-cols-1 md:grid-cols-3 gap-6"><Card className="md:col-span-2"><CardHeader><CardTitle>План регулярных трат</CardTitle><CardDescription>Ежедневные ×30 + ежемесячные</CardDescription></CardHeader><CardContent><div className="text-4xl font-bold mb-5">{fmt(burn.totalMonthly)}</div><div className="grid grid-cols-2 gap-4"><div className="rounded-lg border border-destructive/20 bg-destructive/10 p-4"><div className="text-xs uppercase text-destructive font-bold">Обязательные</div><div className="text-2xl font-mono mt-1">{fmt(burn.essentialTotal)}</div></div><div className="rounded-lg border bg-muted/30 p-4"><div className="text-xs uppercase text-muted-foreground font-bold">Необязательные</div><div className="text-2xl font-mono mt-1">{fmt(burn.variableTotal)}</div></div></div><p className="text-sm text-muted-foreground mt-4">Средний темп: {fmt(burn.totalMonthly / 30)} в день.</p></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">План по категориям</CardTitle></CardHeader><CardContent className="h-[250px] p-0"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chart} dataKey="value" innerRadius={55} outerRadius={80} paddingAngle={2}>{chart.map((x, i) => <Cell key={i} fill={x.color} />)}</Pie><RechartsTooltip formatter={(v: number) => fmt(v)} /></PieChart></ResponsiveContainer></CardContent></Card></div>}
    <Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>Регулярные расходы</CardTitle><CardDescription>Это плановые траты, по которым приложение считает burn rate.</CardDescription></div><div className="flex items-center gap-2 text-sm">Только обязательные <Switch checked={onlyEssential} onCheckedChange={setOnlyEssential} /></div></CardHeader><CardContent>{rows.length === 0 ? <div className="py-10 text-center text-muted-foreground"><Receipt className="h-10 w-10 mx-auto mb-3 opacity-20" />Расходов пока нет.</div> : <div className="border rounded-md overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Категория</TableHead><TableHead>Название</TableHead><TableHead>Период</TableHead><TableHead>Тип</TableHead><TableHead className="text-right">Сумма</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.map(x => { const Icon = CATEGORY_ICONS[x.category] || MoreHorizontal; const daily = x.frequency === "daily"; return <TableRow key={x.id}><TableCell><div className="flex items-center gap-2"><Icon className="h-4 w-4" />{NAMES[x.category] || x.category}</div></TableCell><TableCell>{x.name}</TableCell><TableCell>{daily ? "Каждый день" : "Каждый месяц"}</TableCell><TableCell>{x.isEssential ? <Badge variant="destructive">Обязательный</Badge> : <Badge variant="secondary">Необязательный</Badge>}</TableCell><TableCell className="text-right font-mono">{fmt(x.amount)} <span className="text-xs text-muted-foreground">/ {daily ? "день" : "мес"}</span></TableCell><TableCell><div className="flex justify-end"><Button variant="ghost" size="icon" onClick={() => edit(x)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => del(x.id)}><Trash2 className="h-4 w-4" /></Button></div></TableCell></TableRow>; })}</TableBody></Table></div>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><ArrowDownRight className="h-5 w-5 text-destructive" /> Фактические списания с баланса</CardTitle><CardDescription>Сюда попадает всё, что реально уменьшило свободный остаток: обычные расходы, кредиты и другие операции.</CardDescription></CardHeader><CardContent>{actual.isLoading ? <Skeleton className="h-48 w-full" /> : actualOutflows.length === 0 ? <div className="py-10 text-center text-muted-foreground">Фактических списаний за последние операции пока нет.</div> : <div className="divide-y">{actualOutflows.slice(0, 20).map(tx => <div key={tx.id} className="py-3 flex items-center justify-between gap-4"><div className="flex items-center gap-3 min-w-0"><div className="p-2 rounded-md bg-destructive/10"><CreditCard className="h-4 w-4 text-destructive" /></div><div className="min-w-0"><div className="font-medium truncate">{tx.note || tx.categoryLabel}</div><div className="text-xs text-muted-foreground">{tx.categoryLabel} · {new Date(tx.createdAt).toLocaleString("ru-RU", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}</div></div></div><div className="font-mono font-semibold text-destructive whitespace-nowrap">-{fmt(Math.abs(tx.amount))}</div></div>)}</div>}</CardContent></Card>
  </div>;
}
